users/urls.py
from django.urls import path
from users import views
from django.views.generic import View


urlpatterns = [
    path('employer/', views.employerRegPage,name='employer register'), 
    path('candidate/', views.candidateRegPage,name='candidate register'),
    path('staff/', views.staffRegPage,name='staff register'),
    path('cv/', views.cv,name="cv"),  
    path('',views.usershome,name="home"),
    path('Profile/<str:username>/',views.user_profile,name="Profile"),
    path('Profile/<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('CurrentStatus/',views.CurrentStatus,name='CurrentStatus'),

    path('change_password/', views.change_pass, name='change_password'),

    ]

users/models.py
from .choices import * 
from django.db import models

import os
if not os.path.exists('files'):
    os.makedirs('files')

import json

class CVFormModel(models.Model):
    #user = models.OneToOneField(User)    
    field = models.IntegerField(choices=FIELD_CHOICES, default=1)   
    yearsexp = models.IntegerField(choices=YEARS_CHOICES, default=1)
    education = models.IntegerField(choices=EDUCATION_CHOICES, default=1)
    GitUrl = models.URLField(max_length=25)  
    file = models.FileField(upload_to='files/',default='files/default.pdf')

    def __str__(self):
           return self.GitUrl

from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.db.models import JSONField

class staffUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username=models.CharField(max_length=50)
    USERNAME_FIELD='username'
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    USERNAME_FIELD='username'


class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    username=models.CharField(max_length=50)
    CompanyName = models.CharField(max_length=255)
    employer_id = models.CharField(max_length=200,unique=True)
    is_employer = models.BooleanField(default=True)
    bios=models.TextField(blank=True,default="write you bio here...")
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    USERNAME_FIELD='username'

    def __str__(self):
        return self.user.username

class Candidate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    username=models.CharField(max_length=50)
    candidate_id = models.CharField(max_length=200,unique=True)
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=255)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    is_candidate = models.BooleanField(default=True)
    bios=models.TextField(blank=True,default="write you bio here...")
    cvcandidate = models.OneToOneField(CVFormModel,on_delete=models.CASCADE,blank=True,null=True)
    applyjobs = JSONField(blank=True, default=dict)
    statusforapplyjobs=models.TextField()
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    USERNAME_FIELD='username'
    
    def __str__(self):
        return self.user.username
        
    def set_cv(self,c):
        self.cvcandidate=c
        return self.cvcandidate

    def _str_(self):
        return self.user.username
        
    def get_progress(self):
        return json.loads(self.statusforapplyjobs)

users/templates/appr.html
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Employer Waiting for Confirmation </h1>
            <style type="text/css">
                table.blueTable {
                    border: 0px solid #1C6EA4;
                    background-color: #EEEEEE;
                    width: 100%;
                    text-align: center;
                    border-collapse: collapse;
                  }
                  table.blueTable td, table.blueTable th {
                    border: 1px solid #AAAAAA;
                    padding: 4px 2px;
                  }
                  table.blueTable tbody td {
                    font-size: 19px;
                    font-weight: bold;
                  }
                  table.blueTable tr:nth-child(even) {
                    background: #D0E4F5;
                  }
                  table.blueTable thead {
                    background: #1C6EA4;
                    background: -moz-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
                    background: -webkit-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
                    background: linear-gradient(to bottom, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
                    border-bottom: 2px solid #444444;
                  }
                  table.blueTable thead th {
                    font-size: 18px;
                    font-weight: bold;
                    color: #FFFFFF;
                    text-align: center;
                    border-left: 2px solid #D0E4F5;
                  }
                  table.blueTable thead th:first-child {
                    border-left: none;
                  }
                  
                  table.blueTable tfoot {
                    font-size: 12px;
                    font-weight: bold;
                    color: #FFFFFF;
                    background: #D0E4F5;
                    background: -moz-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
                    background: -webkit-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
                    background: linear-gradient(to bottom, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
                    border-top: 2px solid #444444;
                  }
                  table.blueTable tfoot td {
                    font-size: 12px;
                  }
                  table.blueTable tfoot .links {
                    text-align: right;
                  }
                  table.blueTable tfoot .links a{
                    display: inline-block;
                    background: #1C6EA4;
                    color: #FFFFFF;
                    padding: 2px 8px;
                    border-radius: 5px;
                  }
                  .message p {
                    padding: 10px;
                    border-radius: 5px;
                  }
                  .success {
                    background-color: #dff0d8;
                    color: #3c763d;
                    border: 1px solid #d6e9c6;
                  }
                  .error {
                    background-color: #f2dede;
                    color: #a94442;
                    border: 1px solid #ebccd1;
                  }
                  #messages{
                    background-color: grey;
                    color: #fff;
                    padding: 10px;
                    margin-top: 10px;
                  }
                </style>
                <table class="tg" style="undefined;table-layout: fixed; width: 790px">
                <colgroup>
                <col style="width: 171px">
                <col style="width: 196px">
                <col style="width: 196px">
                <col style="width: 207px">
                <col style="width: 20px">
                </colgroup>


               
                <table class="blueTable">
                  <thead>
                    <tr>
                      <th>Username</th>
                      <th>approved</th>
                    </tr>
                  </thead>
                  {% for data in form %}
                  <form action="update_user_status" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ data.id }}">
                    <tbody>
                      <tr>
                        <td>{{data.username}}</td>
                        <td> <button type="submit" class="save btn btn-default">approved</button></td>
                      </tr>
                    </tbody>                    
                  </form>
                  {% endfor %}
                </table>
                <div class="message">
                  {% for message in messages%}
                    <p id="messages">{{message}}</p>
                  {% endfor %}</div>
                
          <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
          <script>
            {% csrf_token %}

            $('.save').click(function(event) {
              event.preventDefault();
          
              var form = $(this).closest('form');
              var url = form.attr('action');
              var data = form.serialize();
          
              $.ajax({
                url: '/appr/',
                type: 'POST',
                headers: {
                  'X-CSRFToken': getCookie('csrftoken')
                },
                success: function(response) {
                  // Handle the success response
                },
                error: function(response) {
                  // Handle the error response
                },
              });
              
          </script>
          {% endblock content %}

users/templates/candidate_edit_profile.html
<style>
    body {
        background-color: #f5f5f5;
    }

    form {
        width: 50%;
        margin: 20px auto;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        background-color: #fff;
    }

    form h1 {
        margin-bottom: 20px;
        text-align: center;
        color: #555;
    }

    form .form-group {
        margin-bottom: 20px;
    }

    form .form-control {
        width: 100%;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        font-size: 16px;
        background-color: #f5f5f5;
        color: #555;
    }

    form .btn-primary {
        background-color: #337ab7;
        border-color: #2e6da4;
        color: #fff;
        width: 100%;
        border-radius: 5px;
        font-size: 16px;
        padding: 10px;
    }

    form .btn-primary:hover {
        background-color: #286090;
        border-color: #204d74;
    }

    form .btn-primary:active {
        background-color: #204d74;
        border-color: #122b40;
    }
</style>
<center>
<h1>Edit Candidate Profile</h1>
</center>
<form method="post" action="{% url 'edit_profile' candidate.username  %}">
    <center>
    {% csrf_token %}
    {{ form1.as_p }}
    </center>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

users/templates/candidate_profile.html
<style>
  body {
      background-color: #0582CA;
  }

  .profile-info {
      margin: 20px 0;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 20px;
      background-color: #f5f5f5;
  }

  .profile-info h2 {
      margin-bottom: 10px;
  }

  

  .profile-bio {
      margin: 20px 0;
      padding: 20px;
      background-color: #fff;
  }

  .profile-bio textarea {
      width: 100%;
      height: 200px;
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
  }
  .button-container {
      display: flex;
    }
    .button-container button, .button-container input {
      margin: 0 10px;
  }
  .label-value {
      display: flex;
      align-items: center;
    }
    .label-box {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      font-weight: bold;
      width: 300px;
      height: 15px;
    }
    .label-boxReply {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      font-weight: bold;
      width: 300px;
      height: 80px;
    }
    .label1 {
      margin-right: 10px;
    }
    .label1-value {
      display: flex;
      align-items: center;
    }
    .label1-box {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      font-weight: bold;
      width: 300px;
      height: 50px;
    }
    .label1 {
      margin-right: 10px;
      color: red;
    }
    .label2-value {
      display: flex;
      align-items: center;
    }
    .label2-box {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      font-weight: bold;
      width: 300px;
      height: 50px;
    }
    .label2 {
      margin-right: 10px;
    }
    .label3-box {
      border: 2px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      font-weight: bold;
      width: 300px;
      height: 150px;
    }
    #progress {
      position: relative;
      margin-bottom: 30px;
    }
    #progress-bar {
      position: absolute;
      background: lightseagreen;
      height: 35px;
      width: 0%;
      top: 50%;
      left: 0;
    }
    #progress-num {
      margin: 0;
      padding: 0;
      list-style: none;
      display: flex;
      justify-content: space-around;
    }
    #progress-num::before {
      content: "";
      background-color: lightgray;
      position: absolute;
      top: 50%;
      left: 0;
      height: 5px;
      width: 100%;
      z-index: -1;
    }
    #progress-num .step {
      border: 3px solid lightgray;
      border-radius: 100%;
      width: 25px;
      height: 25px;
      line-height: 25px;
      text-align: center;
      background-color: #fff;
      font-family: sans-serif;
      font-size: 14px;  
      position: relative ;
      z-index: 10;
    }
    #progress-num .step.active {
      border-color: lightseagreen;
      background-color: lightseagreen;
      color: #fff;
      width: 25px;
    }
    .btn {
        background: lightgray;    
        border: none;
        border-radius: 3px;
        padding: 6px 12px;   
    }
    .go-back-button:hover {
      background-color: royalblue;
      color: white;
    }
    .interview-button {
      background-color: blue;
      color: white;
      padding: 10px 20px;
      text-decoration: none;
      border-radius: 5px;
      display: inline-block;
  }
  
  .interview-button:hover {
      background-color: darkblue;
  }
</style>

<h1>Hello {{ candidate.user.username }} :-)</h1>
<div style="position:absolute; top:0; right:0;">
  <a href="http://127.0.0.1:8000/" style="position: absolute; top: 5px; right: 10px; background-color: lightgray; padding: 10px 15px; border-radius: 5px; text-decoration: none; color: black; font-weight: bold;">Home</a>
</div>
<div class="profile-info">
  <h2>Basic Information</h2>
  <p>Username: {{ candidate.user.username }}</p>
  <p>Email: {{ candidate.user.email }}</p>
  <p>Date of birth: {{ candidate.date_of_birth }}</p>
  <p>Phone number: {{ candidate.phone_number }}</p>
  <p>First name: {{ candidate.first_name }}</p>
  <p>Last name: {{ candidate.last_name }}</p>
</div>

<div class="profile-bio">
  <h2>Bio</h2><textarea readonly>{{ candidate.bios }}</textarea>
  {% if candidate.user.username == user.username or user.is_staff == True  %}
  <br>
  <div class="button-container">
      <form action="{% url 'change_password' %}">
        <br>
      <button type="submit" class="btn btn-primary">Change Password</button>
      </form> 
      <form action="{% url 'edit_profile' candidate.user.username %}">
          <br>
        <button type="submit" class="btn btn-primary">Edit Profile</button>
      </form> 
      <form action="{% url 'delete_account' %}">
          <br>
        <input type="submit" value="Delete" />
      </form>
    </div>
    
  {% endif %}
</div>
<div class="profile-info">
  <h2>CV Form</h2>
{% if candidate.cvcandidate %}
  <p>Field of work: {{ candidatecv.get_field_display }}</p>
  <p>Years of Experience: {{ candidatecv.get_yearsexp_display }}</p>
  <p>Education: {{ candidatecv.get_education_display }}</p>
  <p>GitHub URL: {{ candidatecv.GitUrl }}</p>  
{% else %}
  <p>No CV</p>
  {% if candidate.user.username == user.username or user.is_staff == True  %}
  <form action="{% url 'cv' %}">
      <button type="submit" class="btn btn-primary">Upload cv</button>
  </form> 
  {% endif %}
{% endif %}
</div>

{% if candidate.user.username == user.username or user.is_staff == True  %}
  <div class="profile-info">
  <h2>All the jobs I submitted:</h2>  <form action="{% url 'list' %}">
    <button type="submit" class="btn btn-primary">Look for jobs</button>
  </form> 
  {% for x in candidate.applyjobs %}
    {% for j in jobs %}
      {% for item in candidate.get_progress %}    

        {% if x == j.slug %}

          <div class="label-value">
            <span class="label">Title:</span>
            <div class="label-box">{{ j.title }}</div>
            </div>
            <div class="label-value">
            <span class="label">Subtitle:</span>
            <div class="label-box">{{ j.subTitle }}</div>
            </div>
            <div class="label-value">
            <span class="label">Body:</span>
            <div class="label3-box">{{ j.body }}</div>
            </div>
            <div class="label-value">
            <span class="label">Date:</span>
            <div class="label-box">{{ j.date }}</div>
            </div>
            <div class="label-value">
            <span class="label">Category:</span>
            <div class="label-box">{{ j.get_category_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Years of Experience:</span>
            <div class="label-box">{{ j.get_yearsexp_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Hybrid:</span>
            <div class="label-box">{{ j.hybrid }}</div>
            </div>
            <div class="label-value">
            <span class="label">Priority:</span>
            <div class="label-box">{{ j.priority }}</div>
            </div>
            <div class="label-value">
            <span class="label">Location:</span>
            <div class="label-box">{{ j.get_location_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Available Amount:</span>
            <div class="label-box">{{ j.availableAmount }}</div>
            </div>
            <h2>Hiring process:</h2>

            <progress value='{{ item }}' max="100" color='red' style="width: 100%; height: 35px; background: orangered;"></progress>
          {% if item == 25 %}
              <h2 style="color: brown;">Resumes accepted</h2>
          {% elif item == 50 %}
              <h2 style="color: orange;">The employer received the resume</h2>
          {% elif item == 75 %}
              <h2 style="color: blue;">You Called for a job interview</h2>
          {% elif item == 100 %}
              <h2 style="color: green;">Good luck! You been hired</h2>
          {% else %}
              <h2 style="color: red;">We apologize, but the recruitment process has stopped</h2>
          {% endif %}
            <p>------------------------------------------------------------------------------------------------------</p>
        {% endif %}
      {% endfor %}
    {% endfor %}
  {% endfor %}
{% endif %}
</div>
{% if candidate.user.username == user.username or user.is_staff == True  %}
<div class="profile-info">
  <h2>My Tickets:</h2><h4>(Red is open,Green is Closed)</h4>
  {% for t in tick %}
      {% if t.user == candidate.user %}
          {% if t.isopen == 0 %}
          <div class="label-value">
              <span class="label">Title:</span>
              <div class="label-box" style="color: green;">{{ t.title }}</div>
            </div>
            <div class="label-value">
              <span class="label">Body:</span>
              <div class="label-box" style="color: green;">{{ t.body }}</div>
            </div>
            <div class="label-value">
              <span class="label">Date:</span>
              <div class="label-box" style="color: green;">{{ t.date }}</div>
            </div>
            <div class="label-value">
              <span class="label">Status:</span>
              <div class="label-box" style="color: green;">Closed</div>
            </div>
            <div class="label-value">
              <span class="label">Reply:</span>
              <div class="label-boxReply" style="color: green;">{{ t.Reply }}</div>
            </div>
              <p>------------------------------------------------------------------------------</p>
          {% else %}
          <div class="label-value">
              <span class="label">Title:</span>
              <div class="label-box" style="color: red;">{{ t.title }}</div>
            </div>
            <div class="label-value">
              <span class="label">Body:</span>
              <div class="label-box" style="color: red;">{{ t.body }}</div>
            </div>
            <div class="label-value">
              <span class="label">Date:</span>
              <div class="label-box" style="color: red;">{{ t.date }}</div>
            </div>
            <div class="label-value">
              <span class="label">Status:</span>
              <div class="label-box" style="color: red;">Open</div>
          </div>
          <p>------------------------------------------------------------------------------</p>
          {% endif %}
      {% endif %}
  {% endfor %}
{% endif %}  
</div>



<script>
var jobs = candidate.applyjobs;
for (var i = 0; i < jobs.length; i++) {
  document.write(jobs[i] + "<br>");
}
</script>

users/templates/delete_account_confirm.html
{% block content %}
    <h1>Delete Account</h1>
    <p>Are you sure you want to delete your account? This action cannot be undone.</p>
    <form method="post" action="{% url 'delete_account' %}">
        {% csrf_token %}
        <input type="submit" value="Delete Account">
    </form>
{% endblock %}

users/templates/employer_edit_profile.html
<style>
    body {
        background-color: #f5f5f5;
    }

    form {
        width: 50%;
        margin: 20px auto;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        background-color: #fff;
    }

    form h1 {
        margin-bottom: 20px;
        text-align: center;
        color: #555;
    }

    form .form-group {
        margin-bottom: 20px;
    }

    form .form-control {
        width: 100%;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        font-size: 16px;
        background-color: #f5f5f5;
        color: #555;
    }

    form .btn-primary {
        background-color: #337ab7;
        border-color: #2e6da4;
        color: #fff;
        width: 100%;
        border-radius: 5px;
        font-size: 16px;
        padding: 10px;
    }

    form .btn-primary:hover {
        background-color: #286090;
        border-color: #204d74;
    }

    form .btn-primary:active {
        background-color: #204d74;
        border-color: #122b40;
    }
</style>
<center>
<h1>Edit Employer Profile</h1>
</center>
<form method="post" action="{% url 'edit_profile' employer.username  %}">
    <center>
    {% csrf_token %}
    {{ form1.as_p }}
    </center>
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

users/templates/employer_profile.html
<style>
    body {
        background-color: #0582CA;
    }

    .profile-info {
        margin: 20px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        background-color: #fff;
    }

    .profile-info h2 {
        margin-bottom: 10px;
    }

    

    .profile-bio {
        margin: 20px 0;
        padding: 20px;
        background-color: #fff;
    }

    .profile-bio textarea {
        width: 100%;
        height: 200px;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
    }
    .button-container {
        display: flex;
      }
      .button-container button, .button-container input {
        margin: 0 10px;
    }
    .label-value {
        display: flex;
        align-items: center;
      }
      .label-box {
        border: 2px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin: 10px;
        font-weight: bold;
        width: 300px;
        height: 20px;
      }
      .label-boxReply {
        border: 2px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin: 10px;
        font-weight: bold;
        width: 300px;
        height: 80px;
      }
      .label1 {
        margin-right: 10px;
      }
      .label1-value {
        display: flex;
        align-items: center;
      }
      .label1-box {
        border: 2px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin: 10px;
        font-weight: bold;
        width: 300px;
        height: 100px;
      }
      .label1 {
        margin-right: 10px;
        color: red;
      }
      .label2-value {
    display: flex;
    align-items: center;
  }
  .label2-box {
    border: 2px solid #ccc;
    border-radius: 5px;
    padding: 10px;
    margin: 10px;
    font-weight: bold;
    width: 300px;
    height: 50px;
  }
  .label2 {
    margin-right: 10px;
  }
  .label3-box {
    border: 2px solid #ccc;
    border-radius: 5px;
    padding: 10px;
    margin: 10px;
    font-weight: bold;
    width: 300px;
    height: 150px;
  }
  .go-back-button:hover {
    background-color: royalblue;
    color: white;
  }
</style>

<h1>Hello {{ employer.user.username }} :-)</h1>
<div style="position:absolute; top:0; right:0;">
  <a href="http://127.0.0.1:8000/" style="position: absolute; top: 5px; right: 10px; background-color: lightgray; padding: 10px 15px; border-radius: 5px; text-decoration: none; color: black; font-weight: bold;">Home</a>
</div>
<div class="profile-info">
    <h2>Basic Information</h2>
    <p>Username: {{ employer.user.username }}</p>
    <p>Email: {{ employer.user.email }}</p>
    <p>Company name: {{ employer.CompanyName }}</p>
    <p>Is Active: {{ employer.user.is_active }}</p>
    <p>Company Id: {{ employer.employer_id }}</p>
    
    <a href="{% url 'CurrentStatus' %}"><button>Current Profile Status Report - PDF file</button></a>


</div>

<div class="profile-bio">
    <h2>Bio:</h2>        
    <textarea readonly>{{ employer.bios }}</textarea>
    <br>
    {% if employer.user.username == user.username or user.is_staff == True  %}

    <div class="button-container">
      <form action="{% url 'change_password' %}">
        <br>
      <button type="submit" class="btn btn-primary">Change Password</button>
      </form> 
        <form action="{% url 'edit_profile' employer.user.username %}">
            <br>
            <button type="submit" class="btn btn-primary">Edit Profile</button>
        </form> 
        <form action="{% url 'delete_account' %}">
            <br>
            <input type="submit" value="Delete" />
        </form>    
        </div>
        {% endif %}
    </div>



<div class="profile-bio">

    <h2>Jobs:</h2>
    <a href="{% url 'upload' %}">
      <button>Upload job</button>
      </a>
    {% for j in job %}
      {% if employer.username == j.owner.username  %}
            <div class="label-value">
            <span class="label">Title:</span>
            <div class="label-box">{{ j.title }}</div>
            </div>
            <div class="label-value">
            <span class="label">Subtitle:</span>
            <div class="label-box">{{ j.subTitle }}</div>
            </div>
            <div class="label-value">
            <span class="label">Body:</span>
            <div class="label3-box">{{ j.body }}</div>
            </div>
            <div class="label-value">
            <span class="label">Date:</span>
            <div class="label-box">{{ j.date }}</div>
            </div>
            <div class="label-value">
            <span class="label">Category:</span>
            <div class="label-box">{{ j.get_category_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Years of Experience:</span>
            <div class="label-box">{{ j.get_yearsexp_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Hybrid:</span>
            <div class="label-box">{{ j.hybrid }}</div>
            </div>
            <div class="label-value">
            <span class="label">Priority:</span>
            <div class="label-box">{{ j.get_priority_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Location:</span>
            <div class="label-box">{{ j.get_location_display }}</div>
            </div>
            <div class="label-value">
            <span class="label">Available Amount:</span>
            <div class="label-box">{{ j.availableAmount }}</div>
            </div>
            
            <a href="{% url 'update' j %}">
              <button>Edit job</button>
              </a>
          <a href="{% url 'deleteJob' j  %}">
              <button>Delete Job</button>
              </a>
              <p>------------------------------------------------------------------------------------------------------</p>

      {% endif %}
    {% endfor %}
    </div>    

{% if employer.user.username == user.username or user.is_staff == True  %}
<div class="profile-info">
    <h2>My Tickets:</h2><h4>(Red is open,Green is Closed)</h4>
    {% for t in tick %}
        {% if t.user == employer.user %}
            {% if t.isopen == 0 %}
            <div class="label-value">
                <span class="label">Title:</span>
                <div class="label-box" style="color: green;">{{ t.title }}</div>
              </div>
              <div class="label-value">
                <span class="label">Body:</span>
                <div class="label-box" style="color: green;">{{ t.body }}</div>
              </div>
              <div class="label-value">
                <span class="label">Date:</span>
                <div class="label-box" style="color: green;">{{ t.date }}</div>
              </div>
              <div class="label-value">
                <span class="label">Status:</span>
                <div class="label-box" style="color: green;">Closed</div>
              </div>
              <div class="label-value">
                <span class="label">Reply:</span>
                <div class="label-boxReply" style="color: green;">{{ t.Reply }}</div>
              </div>
                <p>------------------------------------------------------------------------------</p>
            {% else %}
            <div class="label-value">
                <span class="label">Title:</span>
                <div class="label-box" style="color: red;">{{ t.title }}</div>
              </div>
              <div class="label-value">
                <span class="label">Body:</span>
                <div class="label-box" style="color: red;">{{ t.body }}</div>
              </div>
              <div class="label-value">
                <span class="label">Date:</span>
                <div class="label-box" style="color: red;">{{ t.date }}</div>
              </div>
              <div class="label-value">
                <span class="label">Status:</span>
                <div class="label-box" style="color: red;">Open</div>
            </div>
            <p>------------------------------------------------------------------------------</p>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endif %}  
</div>

</form>

users/templates/users.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"
        <title>users in the house!</title>
    </head>
    <body>
        <h1>This is users page</h1>
        <p>Welcome to JHS</p>
        <img src="https://i.ibb.co/54PLw9C/jhs-logo.png" alt="jhs-logo" border="0">
    </body>
</html>