jobs/urls.py
from django.urls import path
from . import views
from .views import job_details
#from jobs import views

urlpatterns = [
    path('upload/',views.uploadJob,name='upload'),
    path('update/<str:upload_id>',views.updateJob,name='update'),
    path('',views.Upload_list,name='list'),
    path('<str:slug>',views.job_details,name='job_details'),
    path('success/',views.success,name='success'),
    path('deleteJob/<str:upload_id>',views.deleteJob,name='deleteJob'),
    path('ApllyCv/<str:upload_id>',views.applyCv,name='ApllyCv'),
    path('jobsCsvFile/',views.jobscsvFile,name='jobscsvFile'),
    path('jobsLocationPdfFile/',views.jobsLocationPdfFile,name='jobsLocationPdfFile'),
    path('jobsPriorityPdfFile/',views.jobsPriorityPdfFile,name='jobsPriorityPdfFile'),
    path('update_user/<str:username>', views.update_user, name='update_user'),
    path('abort_user/<str:username>', views.abort_user, name='abort_user'),
    path('hired/<str:username>',views.hired_user,name='hired_user'),
]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser,User,BaseUserManager, AbstractBaseUser
from decimal import Decimal
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.forms import UserCreationForm #user create from django firms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .choices import * 
from decimal import *
from users.models import Employer,Candidate



class Upload(models.Model): #The dataBase knows to create a table for this model
    title=models.CharField(max_length=60,null=True)
    subTitle=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    body=models.TextField(max_length=200)
    date=models.DateTimeField(auto_now_add=True) #automaticly applied
    category = models.IntegerField(choices=FIELD_CHOICES, default=1)  
    salaryRange = models.IntegerField(choices=SALARY_CHOICES, default=1)   
    yearsexp = models.IntegerField(choices=YEARS_CHOICES, default=1)
    education = models.IntegerField(choices=EDUCATION_CHOICES, default=1)
    time=models.IntegerField(choices=TIME_CHOICES, default=1)
    hybrid=models.BooleanField(default=True)
    priority=models.IntegerField(choices=PRIORITY_CHOICES,default=1)
    owner=models.ForeignKey(Employer, on_delete=models.CASCADE, default=1, related_name='employer')
    location=models.IntegerField(choices=CITIES, default=1)
    viewsCounter=models.IntegerField(default=0)
    availableAmount = models.DecimalField(max_digits=2, decimal_places=0, default=Decimal('5'))
    notification=models.DecimalField(max_digits=3 ,decimal_places=0, default=Decimal('5'))
    applycandiadteuser = models.ManyToManyField(Candidate, blank=True)
    notification_count = models.IntegerField(default=0)  

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+'...' #take from 0 to 50 characters

    def get_absolute_url(self):
        return reverse("upload_detail", kwargs={"slug": self.slug})

jobs/templates/jobs/Upload_list.html
<html>
  <style>
    .go-back-button:hover {
      background-color: royalblue;
      color: white;
    }
  </style>
    <center>
      <div style="position:absolute; top:0; right:0;">
        <a href="http://127.0.0.1:8000/" style="position: absolute; top: 5px; right: 10px; background-color: lightgray; padding: 10px 15px; border-radius: 5px; text-decoration: none; color: black; font-weight: bold;">Home</a>
      </div>
      
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">    </head>
        <style>
         h1 {
            color: green;
            font-size: 50px;
          }
        </style>
        
      <body><br><br><br>
        <h1>Welcome to JHS Job Offers</h1>
        <a href="{% url 'jobscsvFile' %}"><button>all jobs- Excel File</button></a>
        <a href="{% url 'jobsLocationPdfFile' %}"><button>jobs by location Pdf File</button></a>
        <a href="{% url 'jobsPriorityPdfFile' %}"><button>jobs by Priority Pdf File</button></a>

        <br/>

        <div class="uploads">
          <form method="post">
              {% csrf_token %}
              <br/>
              <label for="sort_field">Sort by:</label>
              <select name="sort_field" id="sort_field">
                <option value="title">Title</option>
                <option value="date">Date</option>
                <option value="salaryRange">Salary Range</option>
                <option value="yearsexp">Years of expirience</option>
                <option value="time">Job Type</option>
                <option value="hybrid">Hybrid</option>
                <option value="viewsCounter">Views</option>
                

              </select>
              <label for="sort_order">Order:</label>
              <select name="sort_order" id="sort_order">
                <option value="ascending">Low To High</option>
                <option value="descending">High To Low</option>
              </select>
              <input type="submit" value="Sort">
            </form>

             
                <br/>
            {% if request.user.employer.is_employer %}    
            <a href="{% url 'upload' %}">
            <button>Upload job</button>
            </a>
            {%endif%}
            <br/><br/> 
            {% for upload in uploads %}
              
            <div class="card bg-light" style="width: 30rem;">
                <div class="card-body">
                  <h5 class="card-title"><h2><strong>{{upload.title}}</strong></h2></h5>
                  <p class="card-text"><strong>{{upload.snippet}}</strong></p>
                  <p class="card-text"><strong>Date: </strong>{{upload.date}}</p>
                  <p class="card-text"><strong>Salary Range: </strong>{{upload.get_salaryRange_display}}</p>
                  <p class="card-text"><strong>Years of expirience:</strong>  {{upload.get_yearsexp_display}}</p>
                  <p class="card-text"><strong>Job Type: </strong>{{upload.get_time_display}}</p>
                  <p class="card-text"><strong>Hybrid: </strong>{{upload.hybrid}}</p>
                  <p class="card-text"><strong>Location: </strong>{{upload.get_location_display}}</p>
                 
                  <p>{{ upload.viewsCounter }}<i class="fa fa-eye" aria-hidden="true"></i></p>



                  <a href="{% url 'job_details' upload  %}" class="btn btn-primary">Show More..</a>
                </div>
              </div>


             
                <br/><br/>
            {% endfor %}


                

            
         </div>
        </body>
    </center>
</html>

jobs/templates/jobs/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Upload list</title>
        <link rel="stylsheet" href="{%/static/admin/css/'style2.css'%}">
    </head>
    <body>
        <div class="wrapper">
            <h1><a href="{% path 'list' %}">jobs</a></h1>
           {% block content %} 
            {% endblock %}
        </div>
    </body>
 </html>

jobs/templates/jobs/hired.html
<html>
    <head>
        <center>
        <meta charset="utf-8">
        <link rel="stylsheet" href="/static/admin/css/style2.css">
    </head>
    <body> 
        <h1>The user Hired for you commpany<br> Thank you - Jhs team!</h1>

        <a href="{% url 'list' %}">
            <button>Back to JobList</button>
            </a>
        
    </body></center>
</html>

jobs/templates/jobs/jobsDetails.html
<html>
    <head>
        <center>
        <meta charset="utf-8">
        <title>Upload list</title>
        <link rel="stylsheet" href="/static/admin/css/style2.css">
    </head>
    <style>
        table.blueTable {
            border: 0px solid #1C6EA4;
            background-color: #EEEEEE;
            width: 100%;
            text-align: center;
            border-collapse: collapse;
          }
          table.blueTable td, table.blueTable th {
            border: 1px solid #AAAAAA;
            padding: 4px 2px;
          }
          table.blueTable tbody td {
            font-size: 19px;
            font-weight: bold;
          }
          table.blueTable tr:nth-child(even) {
            background: #D0E4F5;
          }
          table.blueTable thead {
            background: #1C6EA4;
            background: -moz-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
            background: -webkit-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
            background: linear-gradient(to bottom, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
            border-bottom: 2px solid #444444;
          }
          table.blueTable thead th {
            font-size: 18px;
            font-weight: bold;
            color: #FFFFFF;
            text-align: center;
            border-left: 2px solid #D0E4F5;
          }
          table.blueTable thead th:first-child {
            border-left: none;
          }
          
          table.blueTable tfoot {
            font-size: 12px;
            font-weight: bold;
            color: #FFFFFF;
            background: #D0E4F5;
            background: -moz-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
            background: -webkit-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
            background: linear-gradient(to bottom, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
            border-top: 2px solid #444444;
          }
          table.blueTable tfoot td {
            font-size: 12px;
          }
          table.blueTable tfoot .links {
            text-align: right;
          }
          table.blueTable tfoot .links a{
            display: inline-block;
            background: #1C6EA4;
            color: #FFFFFF;
            padding: 2px 8px;
            border-radius: 5px;
          }
          .interview-button[disabled]{
            background-color: gray;
         }
        </style>
    <body> 
        <div class="jobs-details">
            <div class="job">
              
                <h2>{{job.subTitle}}</h2>
                <small>By:
                    {{job.owner.username}}
                </small>
                <p><h3>job description: </h3>{{job.body}}</p>
                <p>category: {{job.get_category_display}}</p>

                <p>Salary range: {{job.get_salaryRange_display}}</p>

                <p>date of publish: {{job.date}}</p>

                <p>Years of expirience: {{job.get_yearsexp_display}}</p>
                <p>Education: {{job.education}}</p>
                <p>Time: {{job.get_time_display}}</p>
                <p>Location: {{job.get_location_display}}</p>
                <p>Avaliable Amount: {{job.availableAmount }}</p>

            </div>
        </div>

        {% if request.user.is_authenticated %}
          {% if request.user.employer.is_employer and request.user.employer.username == job.owner.username %}
                  <a href="{% url 'update' job.title %}">
                    <button>Edit job</button>
                    </a>
               
                <a href="{% url 'deleteJob' job  %}">
                    <button>Delete Job</button>
                    </a>
                <br>
          {% endif %}
          {% if request.user.candidate.is_candidate %}
              {% if job.availableAmount > 0 %}
                  <a href="{% url 'ApllyCv' job  %}">
                  <button>Apply CV</button>
                  </a>
              {% endif %}
          {% endif %}
          <br>
            
          {% if request.user.employer.is_employer and request.user.employer.username == job.owner.username %}
            <button id="button">Resume pending</button>
            <div id="myDiv" style="display: none;">
                <table class="blueTable">
                    <br>
                    <br>
                    <thead>
                    <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>first name</th>
                    <th>last name</th>
                    <th>phone</th>
                    <th>link</th>
                        
                    </tr>
                    </thead>
                    {% for d in job.applycandiadteuser.all %}
                    <tbody>
                        <tr>
                        <td>{{d.username}}</td>
                        <td>{{d.email}}</td>
                        <td>{{d.first_name}}</td>
                        <td>{{d.last_name}}</td>
                        <td>{{d.phone_number}}</td>
                        <td><a href="{% url 'Profile' d.username  %}">
                          <button>Profile</button>
                          <form action="{% url 'update_user' d.username %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="status" value="accepted">
                            <input type="hidden" name="jobtitle" value="{{ job.title }}">
                            <button type="submit">Accept</button>
                            <button type="submit">Interview</button>
                        </form>
                        <form action="{% url 'abort_user' d.username %}" method="post">
                          {% csrf_token %}
                          <input type="hidden" name="status" value="accepted">
                          <input type="hidden" name="jobtitle" value="{{ job.title }}">
                          <button type="submit">Reject</button>
                      </form>
                      <form action="{% url 'hired_user' d.username %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="status" value="accepted">
                        <input type="hidden" name="jobtitle" value="{{ job.title }}">
                        <button type="submit">Hired</button>
                    </form>
                      </tr>
                  </tbody>                    
                    
                    {% endfor %}
                </table>
            </div>

          {% endif %}
        {% endif %}
        <br/><br/>
        <br/><br/>
        <a href="{% url 'list' %}">
            <button>Back to JobList</button>
            </a>
        
    </body></center>
    <script>
      document.getElementById("button").addEventListener("click", function() {
        var x = document.getElementById("myDiv");
        if (x.style.display === "none") {
          x.style.display = "block";
        } else {
          x.style.display = "none";
        }
      });
      function disableButton() {
        document.getElementById("button").disabled = true;
        document.getElementById("button").classList.add("disabled");
    }
    </script>
</html>

jobs/templates/jobs/success.html
<html>
    <head>
        <style>
            h1 {
               color: green;
               font-size: 50px;
             }
           </style>
   
        <center>
        <meta charset="utf-8">
        <link rel="stylsheet" href="/static/admin/css/style2.css">
    </head>
    <body> 
        <h1>the transaction completed successfully</h1>

        <a href="{% url 'list' %}">
            <button>Back to JobList</button>
            </a>
        
    </body></center>
</html>

jobs/templates/jobs/updateJob.html
<!DOCTYPE html>
<html>
        <style>
        h1 {
            color: green;
            font-size: 50px;
            }
        </style>

    <head>
        <center>
    </head>
    <body>
        <h1>{{job.subTitle}}</h1>
        <form action="" method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <br/>
            <input type="submit" value="Submit" class="btn btn-secondary">


        </form>
       
        
        <br>
        <a href="{% url 'list' %}">
            <button>Back to JobList</button>
            </a>

    </body></center>
</html>

jobs/templates/jobs/uploadJob.html
<html>
    <head> <center>
        <style>
            h1 {
               color: green;
               font-size: 50px;
             }
           </style>
   
        <meta charset="utf-8">
        <title>UploadJob</title>
    </head>
    <body>
        <div><b><textarea:justify>

       
                <h1>Upload Your New Job</h1>
             
                   
                    {% if submitted %}
                        your Upload was submitted successfuly!!
                    {% else }

                    {% endif %}
                        <form action="" method=POST>
                            {% csrf_token %}
                            {{ form.as_p }}

                            <br/>
                            <input type="submit" value="Submit" class="btn btn-secondary">
                        </form>
       
          
               
               
            <a href="{% url 'list' %}">
                    <button>Back to JobList</button>
                    </a>
                 </textarea:justify>
        </div>
    </body></center>
</html>